### ISSUE TITLE
Memory assignment for cluster

### ISSUE THREAD

**Issue by landmanf** [AleSR13/AMR_annotation#4]
In start_annotation.sh no memory is specified when command is send to the cluster. 
Could have possible consequences with runs being terminated.
current command:
--drmaa ' -q bio -n {threads} -R \'span[hosts=1]\'
should have this added:
-R 'rusage[mem=48G]'
With 48G or something else being declared in something like {mem}

**Comment by AleSR13** [comment]
I assigned the memory but that turned out not to be the problem. Instead, a bug in the user's conda settings were causing the killed runs.
